<script setup>
import { computed } from 'vue'
import AppIcon from './AppIcon.vue'

const props = defineProps({
  open: {
    type: Boolean,
    default: false,
  },
  candidateName: {
    type: String,
    default: 'Sarah Johnson',
  },
  candidateRole: {
    type: String,
    default: 'Senior Product Designer',
  },
  candidateAppliedOn: {
    type: String,
    default: '10 May 2025',
  },
})

const emit = defineEmits(['close', 'add-notes', 'open-feedback', 'move-shortlisted'])

const candidateInitials = computed(() => (
  props.candidateName
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? '')
    .join('')
))

const keyFindings = [
  { icon: 'heart', title: 'Motivation & Interest', note: 'Shows strong interest in the role and company mission.', status: 'Strong', tone: 'green' },
  { icon: 'message', title: 'Communication', note: 'Clear, structured answers with great articulation.', status: 'Strong', tone: 'green' },
  { icon: 'briefcase', title: 'Experience Relevance', note: '8 years of product design experience, highly relevant.', status: 'Aligned', tone: 'blue' },
  { icon: 'wallet', title: 'Salary Expectations', note: 'Expectations within the approved budget range.', status: 'Aligned', tone: 'blue' },
  { icon: 'calendar', title: 'Availability', note: 'Available to start within 4 weeks.', status: 'Confirmed', tone: 'green' },
  { icon: 'user-check', title: 'Culture Add', note: 'Values and mindset align well with the team.', status: 'Good Fit', tone: 'green' },
]

const highlights = [
  'Strong design systems and UI/UX expertise',
  'Led design in fast-paced product teams',
  'Great portfolio with measurable impact',
  'Excellent stakeholder communication',
  'Problem solving approach is structured',
]

const concerns = [
  'Limited B2B SaaS experience',
  'Has not worked on marketplace products',
  'Wants more clarity on growth path',
]

const candidateQuestions = [
  'How is product success measured?',
  'What does the design team roadmap look like?',
  'How are design decisions shared with engineering?',
]

const conversationInsights = [
  { label: 'Talk-to-Listen Ratio', value: '38%', note: 'Good balance', tone: 'green', progress: 38 },
  { label: 'Energy & Enthusiasm', value: 'High', note: 'Very engaged', tone: 'violet', progress: 88 },
  { label: 'Confidence', value: 'High', note: 'Consistent throughout', tone: 'blue', progress: 84 },
  { label: 'Clarity of Answers', value: 'Strong', note: 'Clear and concise', tone: 'green', progress: 92 },
]

const interviewFocus = [
  'Dive deeper into product strategy experience',
  'Assess technical collaboration with engineering',
  'Explore decision making and prioritization',
  'Validate leadership examples and coaching style',
]

function closeOverlay() {
  emit('close')
}

function addRecruiterNotes() {
  emit('add-notes')
  emit('close')
}

function openFeedback() {
  emit('open-feedback')
  emit('close')
}

function moveShortlisted() {
  emit('move-shortlisted')
  emit('close')
}
</script>

<template>
  <Teleport to="body">
    <div v-if="open" class="ai-screening-summary-overlay" @click.self="closeOverlay">
      <section class="ai-screening-summary-modal">
        <header class="ai-screening-summary-modal__head">
          <div class="ai-screening-summary-modal__title">
            <span class="ai-screening-summary-modal__icon">
              <AppIcon name="document" :size="18" />
            </span>
            <div>
              <div class="ai-screening-summary-modal__title-row">
                <h2>AI Screening Summary</h2>
                <span class="ai-screening-summary-modal__badge">Generated by NitroSync AI</span>
              </div>
              <p>Intelligence from AI phone screening conducted on our platform</p>
            </div>
          </div>

          <button class="ai-screening-summary-modal__close" type="button" aria-label="Close AI screening summary" @click="closeOverlay">
            <AppIcon name="close" :size="18" />
          </button>
        </header>

        <div class="ai-screening-summary-modal__body">
          <section class="ai-screening-summary-top">
            <article class="ai-screening-summary-candidate">
              <div class="ai-screening-summary-candidate__identity">
                <span class="ai-screening-summary-candidate__avatar">{{ candidateInitials }}</span>
                <div>
                  <strong>{{ candidateName }}</strong>
                  <span>{{ candidateRole }}</span>
                </div>
              </div>
              <span class="ai-screening-summary-candidate__status">Screening Complete</span>
              <div class="ai-screening-summary-candidate__meta">
                <small><AppIcon name="calendar" :size="12" /> {{ candidateAppliedOn }}</small>
                <small><AppIcon name="clock" :size="12" /> 30 Minutes</small>
                <small><AppIcon name="phone" :size="12" /> AI Phone Screening</small>
              </div>
            </article>

            <article class="ai-screening-summary-outcome">
              <small>Screening Outcome</small>
              <strong>Strong Proceed</strong>
              <p>Candidate successfully passed screening requirements.</p>
              <div class="ai-screening-summary-outcome__confidence">
                <span>Confidence: High</span>
                <i />
                <i />
                <i />
              </div>
            </article>

            <article class="ai-screening-summary-next">
              <small>Recommended Next Step</small>
              <strong>Move to Hiring Manager Review</strong>
              <p>Candidate meets core requirements and shows strong potential.</p>
              <div class="ai-screening-summary-next__actions">
                <button class="ai-screening-summary-button ai-screening-summary-button--primary" type="button" @click="moveShortlisted">
                  <span>Move to Shortlisted</span>
                  <AppIcon name="chevronRight" :size="14" />
                </button>
                <button class="ai-screening-summary-button ai-screening-summary-button--ghost" type="button" @click="openFeedback">
                  <span>Share Feedback</span>
                </button>
              </div>
            </article>
          </section>

          <div class="ai-screening-summary-grid">
            <section class="ai-screening-summary-card">
              <h3>Key Findings</h3>
              <div class="ai-screening-summary-findings">
                <article v-for="item in keyFindings" :key="item.title" class="ai-screening-summary-finding">
                  <span class="ai-screening-summary-finding__icon" :class="`is-${item.tone}`">
                    <AppIcon :name="item.icon" :size="14" />
                  </span>
                  <div class="ai-screening-summary-finding__copy">
                    <strong>{{ item.title }}</strong>
                    <p>{{ item.note }}</p>
                  </div>
                  <em :class="`is-${item.tone}`">{{ item.status }}</em>
                </article>
              </div>
            </section>

            <section class="ai-screening-summary-card">
              <div class="ai-screening-summary-split">
                <div>
                  <h3>Highlights</h3>
                  <ul class="ai-screening-summary-list">
                    <li v-for="item in highlights" :key="item">
                      <AppIcon name="checkCircle" :size="12" />
                      <span>{{ item }}</span>
                    </li>
                  </ul>
                </div>

                <div>
                  <h3>Potential Concerns</h3>
                  <ul class="ai-screening-summary-list is-warning">
                    <li v-for="item in concerns" :key="item">
                      <AppIcon name="alert" :size="12" />
                      <span>{{ item }}</span>
                    </li>
                  </ul>
                </div>
              </div>
            </section>

            <section class="ai-screening-summary-card">
              <div class="ai-screening-summary-card__head">
                <h3>AI Conversation Insights</h3>
                <button type="button">View Timeline</button>
              </div>
              <div class="ai-screening-summary-insights">
                <article v-for="item in conversationInsights" :key="item.label" class="ai-screening-summary-insight">
                  <div class="ai-screening-summary-insight__head">
                    <strong>{{ item.label }}</strong>
                    <span>{{ item.value }}</span>
                  </div>
                  <div class="ai-screening-summary-insight__bar">
                    <i :class="`is-${item.tone}`" :style="{ width: `${item.progress}%` }" />
                  </div>
                  <small>{{ item.note }}</small>
                </article>
              </div>
            </section>

            <section class="ai-screening-summary-card">
              <h3>Candidate Questions</h3>
              <ul class="ai-screening-summary-links">
                <li v-for="item in candidateQuestions" :key="item">
                  <AppIcon name="message" :size="12" />
                  <span>{{ item }}</span>
                </li>
              </ul>
            </section>

            <section class="ai-screening-summary-card">
              <h3>Suggested Interview Focus</h3>
              <ul class="ai-screening-summary-links">
                <li v-for="item in interviewFocus" :key="item">
                  <AppIcon name="sparkles" :size="12" />
                  <span>{{ item }}</span>
                </li>
              </ul>
            </section>
          </div>
        </div>

        <footer class="ai-screening-summary-modal__footer">
          <div class="ai-screening-summary-modal__note">
            <AppIcon name="info" :size="14" />
            <span>This summary is AI-generated based on the screening conversation. Review before making a hiring decision.</span>
          </div>

          <div class="ai-screening-summary-modal__actions">
            <button class="ai-screening-summary-button ai-screening-summary-button--ghost ai-screening-summary-button--footer-ghost" type="button" @click="addRecruiterNotes">
              <span>Add Recruiter Notes</span>
            </button>
            <button class="ai-screening-summary-button ai-screening-summary-button--ghost ai-screening-summary-button--footer-ghost" type="button">
              <span>Download Report</span>
            </button>
            <button class="ai-screening-summary-button ai-screening-summary-button--primary ai-screening-summary-button--footer-primary" type="button" @click="moveShortlisted">
              <span>Move to Shortlisted</span>
              <AppIcon name="chevronRight" :size="14" />
            </button>
          </div>
        </footer>
      </section>
    </div>
  </Teleport>
</template>

<style>
.ai-screening-summary-overlay {
  position: fixed;
  inset: 0;
  z-index: 1450;
  display: grid;
  place-items: center;
  overflow: auto;
  padding: 24px;
  background: rgba(19, 26, 41, 0.56);
  backdrop-filter: blur(5px);
}

.ai-screening-summary-modal {
  width: min(100%, 1120px);
  max-height: calc(100vh - 48px);
  display: grid;
  grid-template-rows: auto minmax(0, 1fr) auto;
  border: 1px solid #e8edf5;
  border-top: 4px solid #2a84f7;
  border-radius: 22px;
  overflow: hidden;
  background: #fff;
  box-shadow: 0 32px 90px rgba(15, 23, 42, 0.22);
}

.ai-screening-summary-modal__head,
.ai-screening-summary-modal__title,
.ai-screening-summary-modal__title-row,
.ai-screening-summary-candidate__identity,
.ai-screening-summary-candidate__meta,
.ai-screening-summary-outcome__confidence,
.ai-screening-summary-next__actions,
.ai-screening-summary-finding,
.ai-screening-summary-finding__copy,
.ai-screening-summary-split,
.ai-screening-summary-card__head,
.ai-screening-summary-list li,
.ai-screening-summary-links li,
.ai-screening-summary-modal__footer,
.ai-screening-summary-modal__note,
.ai-screening-summary-modal__actions,
.ai-screening-summary-button {
  display: flex;
  align-items: center;
}

.ai-screening-summary-modal__head,
.ai-screening-summary-card__head,
.ai-screening-summary-modal__footer {
  justify-content: space-between;
}

.ai-screening-summary-modal__head {
  padding: 18px 22px;
  border-bottom: 1px solid #edf2fb;
}

.ai-screening-summary-modal__title {
  gap: 12px;
}

.ai-screening-summary-modal__icon {
  width: 36px;
  height: 36px;
  display: grid;
  place-items: center;
  border-radius: 11px;
  background: #eef3ff;
  color: #5d6ef5;
}

.ai-screening-summary-modal__title-row {
  gap: 10px;
  flex-wrap: wrap;
}

.ai-screening-summary-modal__title h2,
.ai-screening-summary-top strong,
.ai-screening-summary-card h3,
.ai-screening-summary-finding__copy strong,
.ai-screening-summary-insight__head strong {
  margin: 0;
  color: #1f2940;
}

.ai-screening-summary-modal__title h2 {
  font-size: 20px;
  font-weight: 700;
}

.ai-screening-summary-modal__badge {
  padding: 3px 8px;
  border-radius: 999px;
  background: #eef0ff;
  color: #5d6ef5;
  font-size: 9px;
  font-weight: 800;
  text-transform: uppercase;
}

.ai-screening-summary-modal__title p,
.ai-screening-summary-candidate span,
.ai-screening-summary-candidate small,
.ai-screening-summary-outcome p,
.ai-screening-summary-next p,
.ai-screening-summary-finding__copy p,
.ai-screening-summary-links li,
.ai-screening-summary-list li span,
.ai-screening-summary-insight small,
.ai-screening-summary-modal__note span {
  margin: 0;
  color: #7a879e;
  font-size: 12px;
  line-height: 1.5;
}

.ai-screening-summary-modal__close {
  width: 36px;
  height: 36px;
  border: 0;
  border-radius: 12px;
  color: #97a5bb;
  background: transparent;
  cursor: pointer;
}

.ai-screening-summary-modal__body {
  overflow: auto;
  padding: 20px 22px 22px;
}

.ai-screening-summary-top {
  display: grid;
  grid-template-columns: 1.15fr 1fr 1.1fr;
  gap: 14px;
}

.ai-screening-summary-candidate,
.ai-screening-summary-outcome,
.ai-screening-summary-next,
.ai-screening-summary-card {
  padding: 16px;
  border: 1px solid #e8edf5;
  border-radius: 16px;
  background: #fff;
}

.ai-screening-summary-candidate__avatar {
  width: 56px;
  height: 56px;
  display: grid;
  place-items: center;
  border-radius: 14px;
  background: linear-gradient(135deg, #d8a15f 0%, #5f7b89 100%);
  color: #fff;
  font-size: 18px;
  font-weight: 800;
}

.ai-screening-summary-candidate__identity {
  gap: 12px;
}

.ai-screening-summary-candidate__identity strong,
.ai-screening-summary-outcome strong,
.ai-screening-summary-next strong {
  display: block;
  font-size: 15px;
  font-weight: 700;
}

.ai-screening-summary-candidate__status {
  display: inline-flex;
  align-items: center;
  justify-content: center;
  margin-top: 14px;
  padding: 4px 8px;
  border-radius: 999px;
  background: #eaf9f0;
  color: #14a05d;
  font-size: 10px;
  font-weight: 800;
}

.ai-screening-summary-candidate__meta {
  gap: 14px;
  flex-wrap: wrap;
  margin-top: 14px;
}

.ai-screening-summary-candidate__meta small {
  display: inline-flex;
  align-items: center;
  gap: 6px;
}

.ai-screening-summary-outcome {
  background: linear-gradient(180deg, #fbfffd 0%, #f7fff9 100%);
}

.ai-screening-summary-outcome small,
.ai-screening-summary-next small {
  display: block;
  color: #9aa6bd;
  font-size: 10px;
  font-weight: 800;
  text-transform: uppercase;
  letter-spacing: 0.08em;
}

.ai-screening-summary-outcome strong {
  margin-top: 10px;
  color: #11a35b;
  font-size: 28px;
}

.ai-screening-summary-outcome p,
.ai-screening-summary-next p {
  margin-top: 8px;
}

.ai-screening-summary-outcome__confidence {
  gap: 8px;
  margin-top: 16px;
  color: #30415f;
  font-size: 12px;
  font-weight: 700;
}

.ai-screening-summary-outcome__confidence i {
  width: 8px;
  height: 8px;
  border-radius: 999px;
  background: linear-gradient(135deg, #14a05d 0%, #33cb7b 100%);
}

.ai-screening-summary-next__actions {
  gap: 8px;
  margin-top: 16px;
  flex-wrap: wrap;
}

.ai-screening-summary-grid {
  display: grid;
  grid-template-columns: 1.45fr 1.05fr 1fr;
  gap: 14px;
  margin-top: 14px;
}

.ai-screening-summary-card {
  min-width: 0;
}

.ai-screening-summary-card:first-child {
  grid-row: span 2;
}

.ai-screening-summary-card h3 {
  margin-bottom: 12px;
  font-size: 13px;
  font-weight: 700;
}

.ai-screening-summary-findings {
  display: grid;
  gap: 10px;
}

.ai-screening-summary-finding {
  gap: 10px;
  align-items: flex-start;
  padding: 10px 0;
  border-bottom: 1px solid #edf2fb;
}

.ai-screening-summary-finding:last-child {
  border-bottom: 0;
}

.ai-screening-summary-finding__icon {
  width: 28px;
  height: 28px;
  display: grid;
  place-items: center;
  border-radius: 9px;
  flex: 0 0 28px;
}

.ai-screening-summary-finding__icon.is-green {
  color: #15a35d;
  background: #ecfbf2;
}

.ai-screening-summary-finding__icon.is-blue {
  color: #5668ff;
  background: #eef0ff;
}

.ai-screening-summary-finding__copy {
  flex: 1 1 auto;
  min-width: 0;
  flex-direction: column;
  align-items: flex-start;
}

.ai-screening-summary-finding__copy strong {
  font-size: 13px;
  font-weight: 700;
}

.ai-screening-summary-finding__copy p {
  margin-top: 4px;
}

.ai-screening-summary-finding em {
  font-style: normal;
  font-size: 11px;
  font-weight: 700;
}

.ai-screening-summary-finding em.is-green {
  color: #15a35d;
}

.ai-screening-summary-finding em.is-blue {
  color: #5668ff;
}

.ai-screening-summary-split {
  align-items: flex-start;
  gap: 16px;
}

.ai-screening-summary-split > * {
  flex: 1 1 0;
  min-width: 0;
}

.ai-screening-summary-list,
.ai-screening-summary-links {
  display: grid;
  gap: 10px;
  margin: 0;
  padding: 0;
  list-style: none;
}

.ai-screening-summary-list li,
.ai-screening-summary-links li {
  gap: 8px;
  align-items: flex-start;
}

.ai-screening-summary-list svg {
  color: #14a05d;
  flex: 0 0 auto;
  margin-top: 2px;
}

.ai-screening-summary-list.is-warning svg {
  color: #ef8b2d;
}

.ai-screening-summary-links svg {
  color: #5d6ef5;
  flex: 0 0 auto;
  margin-top: 2px;
}

.ai-screening-summary-card__head h3 {
  margin-bottom: 0;
}

.ai-screening-summary-card__head button {
  padding: 0;
  border: 0;
  color: #5d6ef5;
  font: inherit;
  font-size: 11px;
  font-weight: 700;
  text-transform: uppercase;
  background: transparent;
  cursor: pointer;
}

.ai-screening-summary-insights {
  display: grid;
  gap: 14px;
}

.ai-screening-summary-insight__head {
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 10px;
}

.ai-screening-summary-insight__head strong {
  font-size: 12px;
  font-weight: 700;
}

.ai-screening-summary-insight__head span {
  color: #30415f;
  font-size: 12px;
  font-weight: 700;
}

.ai-screening-summary-insight__bar {
  width: 100%;
  height: 4px;
  margin-top: 8px;
  border-radius: 999px;
  background: #edf2fb;
  overflow: hidden;
}

.ai-screening-summary-insight__bar i {
  display: block;
  height: 100%;
  border-radius: inherit;
}

.ai-screening-summary-insight__bar i.is-green {
  background: linear-gradient(90deg, #26c070 0%, #0da65a 100%);
}

.ai-screening-summary-insight__bar i.is-blue {
  background: linear-gradient(90deg, #5b6bff 0%, #4a78ff 100%);
}

.ai-screening-summary-insight__bar i.is-violet {
  background: linear-gradient(90deg, #7958ff 0%, #5f49ff 100%);
}

.ai-screening-summary-insight small {
  display: block;
  margin-top: 6px;
}

.ai-screening-summary-modal__footer {
  gap: 16px;
  padding: 16px 22px 18px;
  border-top: 1px solid #edf2fb;
  align-items: flex-end;
}

.ai-screening-summary-modal__note {
  gap: 8px;
  min-width: 0;
  flex: 1 1 auto;
  padding-right: 12px;
}

.ai-screening-summary-modal__note svg {
  color: #5d6ef5;
  flex: 0 0 auto;
}

.ai-screening-summary-modal__actions {
  display: flex;
  gap: 10px;
  justify-content: end;
  align-items: center;
  flex-wrap: nowrap;
  flex: 0 0 auto;
}

.ai-screening-summary-button {
  justify-content: center;
  gap: 8px;
  min-height: 48px;
  padding: 0 18px;
  border-radius: 12px;
  font: inherit;
  font-size: 13px;
  font-weight: 700;
  white-space: nowrap;
  cursor: pointer;
}

.ai-screening-summary-button--footer-ghost {
  min-width: 184px;
}

.ai-screening-summary-button--footer-primary {
  min-width: 206px;
}

.ai-screening-summary-button--ghost {
  border: 1px solid #dde5f1;
  color: #405070;
  background: #fff;
}

.ai-screening-summary-button--primary {
  border: 0;
  color: #fff;
  background: linear-gradient(90deg, #ff67b5 0%, #ec5eab 100%);
  box-shadow: 0 16px 28px rgba(236, 94, 171, 0.2);
}

@media (max-width: 1080px) {
  .ai-screening-summary-top,
  .ai-screening-summary-grid {
    grid-template-columns: 1fr;
  }

  .ai-screening-summary-card:first-child {
    grid-row: auto;
  }
}

@media (max-width: 720px) {
  .ai-screening-summary-overlay {
    padding: 12px;
  }

  .ai-screening-summary-modal {
    max-height: calc(100vh - 24px);
    border-radius: 18px;
  }

  .ai-screening-summary-modal__head,
  .ai-screening-summary-modal__footer,
  .ai-screening-summary-split {
    flex-direction: column;
    align-items: flex-start;
  }

  .ai-screening-summary-modal__actions {
    width: 100%;
    flex-wrap: wrap;
  }

  .ai-screening-summary-button,
  .ai-screening-summary-button--footer-ghost,
  .ai-screening-summary-button--footer-primary {
    width: 100%;
    min-width: 0;
  }

  .ai-screening-summary-button--footer-primary {
    width: 100%;
  }
}
</style>
