<script setup>
import { computed, ref } from 'vue'
import AppIcon from '../shared/AppIcon.vue'
import PreviewOfferCandidateOverlay from '../shared/PreviewOfferCandidateOverlay.vue'
import { getJobById } from '../../data/jobs'
import '../../styles/create-offer-scratch-launch.css'

const props = defineProps({
  jobId: {
    type: String,
    default: 'ac-1187',
  },
  candidateId: {
    type: String,
    default: '',
  },
  candidateName: {
    type: String,
    default: 'Marvin McKinney',
  },
  candidateRole: {
    type: String,
    default: 'Senior Frontend Developer',
  },
  sourceStage: {
    type: String,
    default: 'Offer',
  },
})

const emit = defineEmits(['back', 'open-source', 'open-launch-offer'])
const previewOfferOverlayOpen = ref(false)

const job = computed(() => getJobById(props.jobId))
const offerLocation = computed(() => job.value?.location || 'San Francisco, CA (Hybrid)')
const offerDepartment = computed(() => job.value?.department || 'Engineering')

const candidateInitials = computed(() => (
  (props.candidateName || 'Marvin McKinney')
    .split(' ')
    .filter(Boolean)
    .slice(0, 2)
    .map((part) => part[0]?.toUpperCase() ?? '')
    .join('')
))

const candidateFirstName = computed(() => props.candidateName.split(' ')[0] || 'Marvin')

const candidateEmail = computed(() => (
  (props.candidateName || 'marvin mckinney')
    .trim()
    .toLowerCase()
    .split(/\s+/)
    .filter(Boolean)
    .join('.')
))

const topStats = [
  ['Total Compensation', '$165,000', 'View full details', 'wallet', 'pink'],
  ['AI Confidence', '95%', 'Very high', 'sparkles', 'violet'],
  ['Acceptance Prediction', '94%', 'Very likely', 'trend-up', 'green'],
  ['Offer Health', 'Excellent', 'Strong offer', 'shield', 'green'],
]

const readinessChecks = [
  'Ready to launch',
  'All approvals completed',
  'Documents validated',
  'Compliance passed',
]

const compensationItems = [
  ['Base Salary', '$145,000', 'Annual'],
  ['Annual Bonus', '12%', 'Target'],
  ['Equity (RSUs)', '750', 'Vested over 4 years'],
  ['Signing Bonus', '$10,000', 'One-time'],
  ['Relocation Bonus', '$5,000', 'One-time'],
]

const employmentRows = computed(() => ([
  ['Position', props.candidateRole],
  ['Department', offerDepartment.value],
  ['Reports To', 'Sarah Johnson'],
  ['Employment Type', 'Full-time'],
  ['Work Location', offerLocation.value],
  ['Start Date', 'June 16, 2025'],
  ['Working Hours', '40 hrs / week'],
  ['Currency', 'USD'],
]))

const benefitTags = [
  ['Medical', 'Premium'],
  ['Dental', 'Premium'],
  ['Vision', 'Premium'],
  ['Vacation', '30 days / year'],
  ['Notice Period', '2 weeks'],
  ['Probation', '3 months'],
  ['Remote Policy', 'Hybrid'],
  ['Confidentiality', 'Standard'],
  ['IP Assignment', 'Included'],
]

const documents = [
  ['Offer Letter', 'PDF - 120 KB', 'pink'],
  ['Employment Agreement', 'PDF - 210 KB', 'blue'],
  ['Benefits Guide', 'PDF - 532 KB', 'green'],
  ['NDA', 'PDF - 98 KB', 'violet'],
  ['Equity Agreement', 'PDF - 156 KB', 'violet'],
]

const deliveryRows = [
  ['Provider', 'DocuSign'],
  ['Delivery Method', 'Email'],
  ['Reminder', 'Every 3 days'],
  ['Offer Expiry', 'May 29, 2025 (14 days)'],
  ['Language', 'English'],
  ['Timezone', 'Candidate timezone'],
]

const approvalRows = [
  ['Hiring Manager', 'Approved'],
  ['HR', 'Approved'],
  ['Finance', 'Approved'],
]

const validationRows = [
  ['Salary verified', 'Passed'],
  ['Internal equity check', 'Passed'],
  ['Budget approval', 'Passed'],
  ['Documents complete', 'Passed'],
  ['Branding applied', 'Passed'],
  ['Compliance verified', 'Passed'],
]

const auditRows = [
  ['AI Draft Generated', 'May 15, 2025 - 09:12 AM'],
  ['Recruiter Edited', 'May 15, 2025 - 09:18 AM'],
  ['Approved by Hiring Manager', 'May 15, 2025 - 09:45 AM'],
  ['Approved by Finance', 'May 15, 2025 - 10:02 AM'],
  ['Ready to Launch', 'May 15, 2025 - 10:05 AM'],
]

const deliveryIcons = ['share', 'mail', 'bell', 'calendar', 'message', 'clock']
</script>

<template>
  <main class="launch-preview-page" @click.self="emit('back')">
    <section class="launch-preview-shell" @click.stop>
      <header class="launch-preview-card launch-preview-header">
        <div class="launch-preview-header__copy">
          <h1>View full details</h1>
          <p>This is exactly what will be sent to {{ candidateName }}.</p>
          <div class="launch-preview-header__meta">
            <span>v1.0</span>
            <small>Generated by NitroSync AI</small>
            <AppIcon name="sparkles" :size="12" />
          </div>
        </div>

        <div class="launch-preview-header__actions">
          <button type="button" class="launch-preview-top-button">
            <AppIcon name="document" :size="14" />
            <span>Download PDF</span>
          </button>
          <button type="button" class="launch-preview-top-button">
            <AppIcon name="copy" :size="14" />
            <span>Print</span>
          </button>
          <button type="button" class="launch-preview-close" aria-label="Close" @click="emit('back')">
            <AppIcon name="close" :size="18" />
          </button>
        </div>
      </header>

      <div class="launch-preview-body">
        <section class="launch-preview-column launch-preview-column--main">
          <section class="launch-preview-top">
          <article class="launch-preview-card launch-preview-hero">
            <div class="launch-preview-hero__candidate">
              <span class="launch-preview-avatar">{{ candidateInitials }}</span>
              <div>
                <strong>{{ candidateName }}</strong>
                <small>{{ candidateRole }}</small>
                <small>{{ offerLocation }} <em>&bull;</em> Full-time</small>
              </div>
            </div>

            <article v-for="item in topStats" :key="item[0]" class="launch-preview-hero__metric">
              <span><AppIcon :name="item[3]" :size="12" /> {{ item[0] }}</span>
              <strong :class="`is-${item[4]}`">{{ item[1] }}</strong>
              <small>{{ item[2] }}</small>
            </article>
          </article>
          </section>

          <div class="launch-preview-banner">
          <AppIcon name="checkCircle" :size="14" />
          <span v-for="item in readinessChecks" :key="item">{{ item }}</span>
          </div>

          <section class="launch-preview-main">
            <article class="launch-preview-card launch-preview-panel">
              <div class="launch-preview-section-head">
                <span class="tone-pink"><AppIcon name="wallet" :size="12" /></span>
                <strong>Compensation</strong>
              </div>

              <div class="launch-preview-compensation">
                <article v-for="item in compensationItems" :key="item[0]">
                  <small>{{ item[0] }}</small>
                  <strong>{{ item[1] }}</strong>
                  <span>{{ item[2] }}</span>
                </article>

                <div class="launch-preview-total-card">
                  <small>Total Compensation</small>
                  <strong>$165,000</strong>
                </div>
              </div>
            </article>

            <article class="launch-preview-card launch-preview-panel">
              <div class="launch-preview-section-head">
                <span class="tone-violet"><AppIcon name="briefcase" :size="12" /></span>
                <strong>Employment Details</strong>
              </div>

              <div class="launch-preview-employment">
                <article v-for="item in employmentRows" :key="item[0]">
                  <small>{{ item[0] }}</small>
                  <strong>{{ item[1] }}</strong>
                </article>
              </div>
            </article>

            <article class="launch-preview-card launch-preview-panel">
              <div class="launch-preview-section-head">
                <span class="tone-violet"><AppIcon name="shield" :size="12" /></span>
                <strong>Benefits &amp; Terms</strong>
              </div>

              <div class="launch-preview-benefits">
                <article v-for="item in benefitTags" :key="item[0]">
                  <strong>{{ item[0] }}</strong>
                  <small>{{ item[1] }}</small>
                </article>
              </div>
            </article>

            <article class="launch-preview-card launch-preview-panel">
              <div class="launch-preview-section-head">
                <span class="tone-orange"><AppIcon name="document" :size="12" /></span>
                <strong>Documents Included</strong>
              </div>

              <div class="launch-preview-documents">
                <article v-for="item in documents" :key="item[0]">
                  <div class="launch-preview-documents__info">
                    <span class="launch-preview-doc-mark" :class="`is-${item[2]}`"><AppIcon name="document" :size="13" /></span>
                    <div>
                      <strong>{{ item[0] }}</strong>
                      <small>{{ item[1] }}</small>
                    </div>
                  </div>

                  <div class="launch-preview-documents__actions">
                    <button type="button">Preview</button>
                    <button type="button" class="icon-only" aria-label="Download">
                      <AppIcon name="document" :size="12" />
                    </button>
                  </div>
                </article>
              </div>
            </article>

            <article class="launch-preview-card launch-preview-panel">
              <div class="launch-preview-section-head">
                <span class="tone-violet"><AppIcon name="mail" :size="12" /></span>
                <strong>Candidate Email Preview</strong>
              </div>

              <div class="launch-preview-email">
                <div class="launch-preview-email__meta">
                  <article><small>Subject</small><strong>Your Offer from NitroSync</strong></article>
                  <article><small>From</small><strong>NitroSync Offers &lt;offers@nitrosync.com&gt;</strong></article>
                  <article><small>To</small><strong>{{ candidateEmail }}@email.com</strong></article>
                  <button type="button" class="launch-preview-email__meta-button" @click="previewOfferOverlayOpen = true">
                    <AppIcon name="eye" :size="13" />
                    <span>Preview Candidate View</span>
                  </button>
                </div>

                <div class="launch-preview-email__body">
                  <div class="launch-preview-email__hero">
                    <div class="launch-preview-email__celebration" aria-hidden="true">
                      <span />
                      <span />
                      <span />
                    </div>
                    <div class="launch-preview-email__copy">
                      <strong>Hi {{ candidateFirstName }},</strong>
                      <p>We&apos;re thrilled to extend this offer for the position of {{ candidateRole }} at NitroSync.</p>
                    </div>
                  </div>
                  <button type="button" @click="previewOfferOverlayOpen = true">Review and Accept Offer</button>
                  <small>This offer will expire on May 29, 2025.</small>
                  <p>If you have any questions, feel free to reach out.</p>
                  <em>The NitroSync Team</em>
                </div>
              </div>
            </article>
          </section>

        </section>

        <section class="launch-preview-column launch-preview-column--side">
          <article class="launch-preview-card launch-preview-side-card launch-preview-delivery-card">
            <div class="launch-preview-section-head">
              <span class="tone-pink"><AppIcon name="share" :size="12" /></span>
              <strong>Delivery Details</strong>
            </div>

            <div class="launch-preview-side-list">
              <article v-for="(item, index) in deliveryRows" :key="item[0]">
                <span><AppIcon :name="deliveryIcons[index]" :size="12" /> {{ item[0] }}</span>
                <strong>{{ item[1] }}</strong>
              </article>
            </div>
          </article>

          <aside class="launch-preview-side">
            <article class="launch-preview-card launch-preview-side-card">
              <div class="launch-preview-section-head">
                <span class="tone-pink"><AppIcon name="users" :size="12" /></span>
                <strong>Approval Summary</strong>
              </div>

              <div class="launch-preview-side-list is-status">
                <article v-for="item in approvalRows" :key="item[0]">
                  <span><AppIcon name="checkCircle" :size="12" /> {{ item[0] }}</span>
                  <strong class="is-green">{{ item[1] }}</strong>
                </article>
              </div>

              <div class="launch-preview-side-note">All approvals completed</div>
            </article>

            <article class="launch-preview-card launch-preview-side-card">
              <div class="launch-preview-section-head">
                <span class="tone-violet"><AppIcon name="sparkles" :size="12" /></span>
                <strong>AI Validation</strong>
              </div>

              <div class="launch-preview-side-list is-status">
                <article v-for="item in validationRows" :key="item[0]">
                  <span><AppIcon name="checkCircle" :size="12" /> {{ item[0] }}</span>
                  <strong class="is-green">{{ item[1] }}</strong>
                </article>
              </div>

              <div class="launch-preview-validation">
                <div class="launch-preview-validation__score">98%</div>
                <div>
                  <strong>Offer is ready to launch</strong>
                  <small>No issues detected</small>
                </div>
              </div>
            </article>

            <article class="launch-preview-card launch-preview-side-card">
              <div class="launch-preview-section-head">
                <span class="tone-pink"><AppIcon name="clock" :size="12" /></span>
                <strong>Audit Trail</strong>
              </div>

              <div class="launch-preview-audit">
                <article v-for="item in auditRows" :key="item[0]">
                  <span class="dot" />
                  <div class="launch-preview-audit__content">
                    <strong>{{ item[0] }}</strong>
                    <small>{{ item[1] }}</small>
                  </div>
                </article>
              </div>
            </article>
          </aside>
        </section>
      </div>

      <footer class="launch-preview-footer">
        <div class="launch-preview-footer__actions">
          <button type="button" class="launch-preview-button" @click="emit('open-source')">Back</button>
          <button type="button" class="launch-preview-button">Save Draft</button>
        </div>

        <button type="button" class="launch-preview-button is-primary" @click="emit('open-launch-offer')">
          <AppIcon name="share" :size="15" />
          <span>Launch Offer</span>
        </button>
      </footer>
    </section>

    <PreviewOfferCandidateOverlay
      :open="previewOfferOverlayOpen"
      :candidate-name="candidateName"
      :candidate-role="candidateRole"
      @close="previewOfferOverlayOpen = false"
    />
  </main>
</template>
